services:
  - type: web
    name: bus-management
    runtime: docker
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: PGHOST
        sync: false
      - key: PGPORT
        value: 5432
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PG_PARAMS
        value: "?sslmode=require"
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
